# Spring
spring:
  main.banner-mode: "off"
  jmx.enabled: false    # Speed up server startup

# Log
logging:
  level.org:
    hibernate:
      SQL: WARN
      type:
        descriptor.sql.BasicBinder: WARN
        value: WARN
      value: WARN
      springframework.web: WARN

# Server
server:
  port: 8080

# H2 Database
spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:

spring.jpa:
  show-sql: false
  open-in-view: false
  properties:
    hibernate:
      cache:
        use_second_level_cache: false   # Speed up server startup
        use_query_cache: false          # Speed up server startup
